apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-28T23:40:47Z"
  labels:
    app: robot-frontend
  name: robot-frontend-service
  namespace: default
  resourceVersion: "14566"
  selfLink: /api/v1/namespaces/default/services/robot-frontend-service
  uid: 7921b067-29cb-11ea-bea6-42010a80004b
spec:
  clusterIP: 10.16.5.34
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31845
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: robot-frontend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.66.203.9
