apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2019-12-28T22:45:03Z"
  generation: 11
  labels:
    app: robot-backend
  name: robot-backend
  namespace: default
  resourceVersion: "623515"
  selfLink: /apis/apps/v1/namespaces/default/deployments/robot-backend
  uid: b01f9137-29c3-11ea-bea6-42010a80004b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: robot-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: robot-backend
    spec:
      containers:
      - image: asia.gcr.io/robot-263409/robot_backend@sha256:b614c2cddeffc6688bfb6b25c496d4a12a074033594b4a0dd6f94a1c9e507664
        imagePullPolicy: IfNotPresent
        name: robot-backend-sha256
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-12-31T00:48:14Z"
    lastUpdateTime: "2019-12-31T00:48:14Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-12-28T22:45:03Z"
    lastUpdateTime: "2019-12-31T00:48:14Z"
    message: ReplicaSet "robot-backend-576b9d6787" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 11
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
