apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2019-12-28T23:38:27Z"
  generation: 7
  labels:
    app: robot-frontend
  name: robot-frontend
  namespace: default
  resourceVersion: "623737"
  selfLink: /apis/apps/v1/namespaces/default/deployments/robot-frontend
  uid: 25a99298-29cb-11ea-bea6-42010a80004b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: robot-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: robot-frontend
    spec:
      containers:
      - image: asia.gcr.io/robot-263409/robot_frontend@sha256:4b80eeed71c4657bdb80443ce585b4e28ddf85bcef529f48035658cf24ae2de2
        imagePullPolicy: IfNotPresent
        name: robot-frontend-sha256
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-12-31T00:49:04Z"
    lastUpdateTime: "2019-12-31T00:49:04Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-12-28T23:38:27Z"
    lastUpdateTime: "2019-12-31T00:49:12Z"
    message: ReplicaSet "robot-frontend-66844974f8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 7
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
