name: Robot Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    
    - name: Build
      run: dotnet build Robot.sln --configuration Release
    
    - name: Test
      run: dotnet test Robot.sln --configuration Release
    
    - name: Publish
      run: dotnet publish Robot.sln --configuration Release
   
    - name: Build Docker Image - Backend
      run: docker build --tag asia.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_BACKEND_APP_NAME }} -f Dockerfile.backend .
    
    - name: Build Docker Image - Frontend
      run: docker build --tag asia.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_FRONTEND_APP_NAME }} -f Dockerfile.frontend .

    - name: Setup gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
  
    - name: Configure docker to authenticate via gcloud
      run: gcloud auth configure-docker
      
    - name: Publish Backend Image
      run: docker push asia.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_BACKEND_APP_NAME }}

    - name: Publish Frontend Image
      run: docker push asia.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_FRONTEND_APP_NAME }}
